apiVersion: v1
kind: Service
metadata:
  name: entelliship-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 #30000-32767
  selector:
    app: entelliship
